homeassistant:
  name: Home
  temperature_unit: C
  time_zone: Europe/London
  unit_system: metric
default_config:
frontend:
  themes: !include_dir_merge_named themes
tts:
  - platform: google_translate
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_booleans.yaml
input_number: !include input_numbers.yaml
lovelace:
  mode: yaml