version: '3'

services:
  dev.web:
    image: node:alpine
    container_name: dev.web
    working_dir: /app
    ports:
      - 8000:8000
    volumes:
      - ../frontend:/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev
    env_file:
      - ../devop/.dev.env
    networks:
      - dev.team3network

  dev.api:
    image: node:alpine
    container_name: dev.api
    working_dir: /api
    ports:
      - 8001:8001
    volumes:
      - ../api:/api
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev
    env_file:
      - ../devop/.dev.env
    networks:
      - dev.team3network

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    ports:
      - 8123:8123
    volumes:
      - ~/.team3config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - dev.team3network

networks:
  dev.team3network:
    name: dev.team3network