version: "3.5"

services:
  dind:
    image: docker:20-dind
    container_name: gitlab.dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2
    volumes:
      - ~/.gitlab-config/data/dind/docker:/var/lib/docker
    networks:
      - gitlab_runner_network

  runner:
    restart: always
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    container_name: gitlab.runner
    volumes:
      - ~/.gitlab-config/config:/etc/gitlab-runner:z
      - ~/.gitlab-config/data/runner/cache:/cache
        ###- /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://dind:2375
    networks:
      - gitlab_runner_network

  register-runner:
    restart: 'no'
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    container_name: gitlab.register-runner
    depends_on:
      - dind
    # environment:
    #   - CI_SERVER_URL=${CI_SERVER_URL}
    #   - REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
    env_file:
      - ~/.gitlab-config/.env
    command:
      - register
      - --non-interactive
      - --locked=false
      - --name=\${RUNNER_NAME}
      - --executor=docker
      - --docker-image=docker:20-dind
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    volumes:
      - ~/.gitlab-config/config:/etc/gitlab-runner:z
      - ~/.gitlab-config/data/dind/docker:/var/lib/docker
    networks:
      - gitlab_runner_network

networks:
  gitlab_runner_network:
    name: gitlab_runner_network